# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlexLayoutPR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlexLayout'

  # Pods for FlexLayoutPR

  target 'FlexLayoutPRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlexLayoutPRUITests' do
    # Pods for testing
  end

end
