# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerShop
  pod 'Alamofire'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'lottie-ios'
end
